/**
 * Script to generate and verify a large Greek word dataset.
 * Run with: node scripts/generateWords.mjs
 * Outputs the verified dataset to stdout / updates greekWords.ts
 */

// Calculation engine (mirrors src/utils/isopsephy.ts)
const LETTER_VALUES = {
  'α':1,'β':2,'γ':3,'δ':4,'ε':5,'ζ':7,'η':8,'θ':9,
  'ι':10,'κ':20,'λ':30,'μ':40,'ν':50,'ξ':60,'ο':70,'π':80,
  'ρ':100,'σ':200,'ς':200,'τ':300,'υ':400,'φ':500,'χ':600,'ψ':700,'ω':800,
};

function calc(word) {
  return word
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .split('')
    .reduce((sum, ch) => sum + (LETTER_VALUES[ch] || 0), 0);
}

// Raw word list: [word, transliteration, meaning, category, interpretationType, notes?]
// Categories: theological | philosophical | virtue | nature | cosmological | concept | body | emotion | number_word | myth
const RAW_WORDS = [
  // ── Already in dataset (kept for reference) ───────────────────────────────
  ['ΘΕΟΣ',      'Theos',       'God',                         'theological',  'historical', 'Central term in Greek theology'],
  ['ΑΓΙΟΣ',     'Hagios',      'Holy',                        'theological',  'mathematical'],
  ['ΑΓΑΘΟΣ',    'Agathos',     'Good',                        'virtue',       'mathematical'],
  ['ΝΟΥΣ',      'Nous',        'Mind, Intellect',             'philosophical','historical'],
  ['ΤΟΠΟΣ',     'Topos',       'Place',                       'concept',      'mathematical'],
  ['ΣΟΦΙΑ',     'Sophia',      'Wisdom',                      'virtue',       'historical'],
  ['ΙΗΣΟΥΣ',    'Iesous',      'Jesus',                       'theological',  'historical', 'Early Christian isopsephy'],
  ['ΛΟΓΟΣ',     'Logos',       'Word, Reason',                'philosophical','historical'],
  ['ΑΓΑΠΗ',     'Agape',       'Love (unconditional)',        'virtue',       'historical'],
  ['ΦΩΣ',       'Phos',        'Light',                       'nature',       'historical'],
  ['ΚΟΣΜΟΣ',    'Kosmos',      'World, Order',                'cosmological', 'historical'],
  ['ΨΥΧΗ',      'Psyche',      'Soul',                        'philosophical','historical'],
  ['ΑΛΗΘΕΙΑ',   'Aletheia',    'Truth',                       'philosophical','historical'],
  ['ΕΙΡΗΝΗ',    'Eirene',      'Peace',                       'virtue',       'mathematical'],
  ['ΧΑΡΑ',      'Chara',       'Joy',                         'virtue',       'mathematical'],
  ['ΑΡΕΤΗ',     'Arete',       'Virtue, Excellence',          'virtue',       'mathematical'],
  ['ΔΙΚΑΙΟΣ',   'Dikaios',     'Just, Righteous',             'virtue',       'mathematical'],
  ['ΚΑΛΟΣ',     'Kalos',       'Beautiful, Good',             'virtue',       'mathematical'],
  ['ΑΓΓΕΛΟΣ',   'Angelos',     'Messenger, Angel',            'theological',  'mathematical'],
  ['ΚΥΡΙΟΣ',    'Kyrios',      'Lord',                        'theological',  'mathematical'],
  ['ΧΡΙΣΤΟΣ',   'Christos',    'Anointed, Christ',            'theological',  'historical'],
  ['ΠΝΕΥΜΑ',    'Pneuma',      'Spirit, Breath',              'theological',  'mathematical'],
  ['ΦΙΛΙΑ',     'Philia',      'Friendship',                  'virtue',       'mathematical'],
  ['ΖΩΗ',       'Zoe',         'Life (spiritual)',            'concept',      'mathematical'],
  ['ΒΙΟΣ',      'Bios',        'Life (biological)',           'concept',      'mathematical'],
  ['ΑΝΘΡΩΠΟΣ',  'Anthropos',   'Human Being',                 'concept',      'mathematical'],
  ['ΠΟΛΙΣ',     'Polis',       'City-State',                  'concept',      'mathematical'],

  // ── Gods & Mythology ──────────────────────────────────────────────────────
  ['ΖΕΥΣ',      'Zeus',        'Zeus, king of the gods',      'myth',         'mathematical'],
  ['ΗΡΑ',       'Hera',        'Hera, queen of gods',         'myth',         'mathematical'],
  ['ΑΡΗΣ',      'Ares',        'Ares, god of war',            'myth',         'mathematical'],
  ['ΑΘΗΝΑ',     'Athena',      'Athena, goddess of wisdom',   'myth',         'mathematical'],
  ['ΑΠΟΛΛΩΝ',   'Apollon',     'Apollo, god of sun and art',  'myth',         'mathematical'],
  ['ΑΡΤΕΜΙΣ',   'Artemis',     'Artemis, goddess of the hunt','myth',         'mathematical'],
  ['ΑΦΡΟΔΙΤΗ',  'Aphrodite',   'Aphrodite, goddess of love',  'myth',         'mathematical'],
  ['ΠΟΣΕΙΔΩΝ',  'Poseidon',    'Poseidon, god of the sea',    'myth',         'mathematical'],
  ['ΕΡΜΗΣ',     'Hermes',      'Hermes, messenger of gods',   'myth',         'mathematical'],
  ['ΗΦΑΙΣΤΟΣ',  'Hephaistos',  'Hephaestus, god of fire/forge','myth',        'mathematical'],
  ['ΔΙΟΝΥΣΟΣ',  'Dionysos',    'Dionysus, god of wine',       'myth',         'mathematical'],
  ['ΔΗΜΗΤΗΡ',   'Demeter',     'Demeter, goddess of harvest', 'myth',         'mathematical'],
  ['ΠΕΡΣΕΦΟΝΗ', 'Persephone',  'Persephone, queen of underworld','myth',      'mathematical'],
  ['ΗΡΑΚΛΗΣ',   'Herakles',    'Heracles, greatest hero',     'myth',         'mathematical'],
  ['ΑΧΙΛΛΕΥΣ',  'Achilleus',   'Achilles, hero of Iliad',     'myth',         'mathematical'],
  ['ΟΔΥΣΣΕΥΣ',  'Odysseus',    'Odysseus, hero of Odyssey',   'myth',         'mathematical'],
  ['ΟΡΦΕΥΣ',    'Orpheus',     'Orpheus, divine musician',    'myth',         'mathematical'],
  ['ΚΡΟΝΟΣ',    'Kronos',      'Cronus, Titan, father of Zeus','myth',        'mathematical'],
  ['ΤΙΤΑΝ',     'Titan',       'Titan (primordial god)',       'myth',         'mathematical'],
  ['ΝΥΞ',       'Nyx',         'Night (primordial goddess)',   'myth',         'mathematical'],
  ['ΕΡΩΣ',      'Eros',        'Eros, god of love',           'myth',         'mathematical'],
  ['ΧΑΟΣ',      'Chaos',       'Chaos (primordial void)',      'myth',         'mathematical'],
  ['ΓΑΙΑ',      'Gaia',        'Gaia, Earth goddess',         'myth',         'mathematical'],
  ['ΟΥΡΑΝΟΣ',   'Ouranos',     'Ouranos, sky god',            'myth',         'mathematical'],
  ['ΘΑΝΑΤΟΣ',   'Thanatos',    'Thanatos, personification of death','myth',   'mathematical'],
  ['ΥΠΝΟΣ',     'Hypnos',      'Hypnos, god of sleep',        'myth',         'mathematical'],
  ['ΜΟΙΡΑ',     'Moira',       'Fate, destiny',               'myth',         'mathematical'],
  ['ΝΕΜΕΣΙΣ',   'Nemesis',     'Nemesis, divine retribution', 'myth',         'mathematical'],
  ['ΝΙΚΗ',      'Nike',        'Victory (goddess)',           'myth',         'mathematical'],
  ['ΤΥΧΗ',      'Tyche',       'Fortune (goddess)',           'myth',         'mathematical'],
  ['ΕΙΛΕΙΘΥΙΑ', 'Eileithyia',  'Goddess of childbirth',       'myth',         'mathematical'],
  ['ΜΟΥΣΑ',     'Mousa',       'Muse (goddess of arts)',      'myth',         'mathematical'],
  ['ΠΑΝΘΕΟΝ',   'Pantheon',    'All the gods',                'myth',         'mathematical'],
  ['ΟΛΥΜΠΟΣ',   'Olympos',     'Mount Olympus',               'myth',         'mathematical'],
  ['ΕΛΥΣΙΟΝ',   'Elysion',     'Elysium (paradise)',          'myth',         'mathematical'],
  ['ΑΙΔΗΣ',     'Aides',       'Hades (underworld)',          'myth',         'mathematical'],
  ['ΣΤΥΞ',      'Styx',        'River Styx',                  'myth',         'mathematical'],
  ['ΛΥΡΑ',      'Lyra',        'Lyre (instrument of Apollo)', 'myth',         'mathematical'],

  // ── Philosophical / Abstract ───────────────────────────────────────────────
  ['ΙΔΕΑ',      'Idea',        'Form, Idea (Platonic)',        'philosophical','historical'],
  ['ΕΙΔΟΣ',     'Eidos',       'Form, Species (Aristotle)',   'philosophical','historical'],
  ['ΥΛΗ',       'Hyle',        'Matter, Material',            'philosophical','historical'],
  ['ΜΟΡΦΗ',     'Morphe',      'Form, Shape',                 'philosophical','historical'],
  ['ΦΥΣΙΣ',     'Physis',      'Nature, Growth',              'philosophical','historical'],
  ['ΑΡΧΗ',      'Arche',       'Beginning, Principle',        'philosophical','historical'],
  ['ΤΕΛΟΣ',     'Telos',       'End, Purpose',                'philosophical','historical'],
  ['ΑΙΤΙΑ',     'Aitia',       'Cause',                       'philosophical','historical'],
  ['ΟΥΣΙΑ',     'Ousia',       'Being, Essence',              'philosophical','historical'],
  ['ΤΟΔΕ',      'Tode',        'This thing (Aristotle)',      'philosophical','historical'],
  ['ΠΡΩΤΗ',     'Prote',       'First (as in first cause)',   'philosophical','mathematical'],
  ['ΔΥΝΑΜΙΣ',   'Dynamis',     'Potentiality, Power',         'philosophical','historical'],
  ['ΕΝΕΡΓΕΙΑ',  'Energeia',    'Actuality, Activity',         'philosophical','historical'],
  ['ΕΝΤΕΛΕΧΕΙΑ','Entelecheia', 'Entelechy (full actuality)',  'philosophical','historical'],
  ['ΕΠΟΧΗ',     'Epoche',      'Suspension of judgment',      'philosophical','historical'],
  ['ΑΤΑΡΑΞΙΑ',  'Ataraxia',    'Tranquility, peace of mind',  'philosophical','historical'],
  ['ΑΠΑΘΕΙΑ',   'Apatheia',    'Freedom from passion',        'philosophical','historical'],
  ['ΕΥΔΑΙΜΟΝΙΑ','Eudaimonia',  'Happiness, Flourishing',      'philosophical','historical'],
  ['ΦΡΟΝΗΣΙΣ',  'Phronesis',   'Practical wisdom',            'philosophical','historical'],
  ['ΓΝΩΣΙΣ',    'Gnosis',      'Knowledge (spiritual)',       'philosophical','historical'],
  ['ΕΠΙΣΤΗΜΗ',  'Episteme',    'Scientific knowledge',        'philosophical','historical'],
  ['ΤΕΧΝΗ',     'Techne',      'Art, Craft, Skill',           'philosophical','historical'],
  ['ΜΙΜΗΣΙΣ',   'Mimesis',     'Imitation, Representation',   'philosophical','historical'],
  ['ΠΟΙΗΣΙΣ',   'Poiesis',     'Making, Creating',            'philosophical','historical'],
  ['ΠΡΑΞΙΣ',    'Praxis',      'Action, Practice',            'philosophical','historical'],
  ['ΘΕΩΡΙΑ',    'Theoria',     'Contemplation, Theory',       'philosophical','historical'],
  ['ΔΙΑΛΟΓΟΣ',  'Dialogos',    'Dialogue',                    'philosophical','historical'],
  ['ΣΥΛΛΟΓΙΣΜΟΣ','Syllogismos','Syllogism',                   'philosophical','historical'],
  ['ΑΠΟΔΕΙΞΙΣ', 'Apodeixis',   'Demonstration, Proof',        'philosophical','historical'],
  ['ΑΝΑΛΟΓΙΑ',  'Analogia',    'Analogy, Proportion',         'philosophical','mathematical'],
  ['ΠΑΡΑΔΕΙΓΜΑ','Paradeigma',  'Example, Paradigm',           'philosophical','historical'],
  ['ΣΚΕΨΙΣ',    'Skepsis',     'Inquiry, Skepticism',         'philosophical','historical'],
  ['ΔΙΑΛΕΚΤΙΚΗ','Dialektike',  'Dialectic',                   'philosophical','historical'],
  ['ΡΗΤΟΡΙΚΗ',  'Rhetorike',   'Rhetoric',                    'philosophical','historical'],
  ['ΛΟΓΙΚΗ',    'Logike',      'Logic',                       'philosophical','historical'],
  ['ΗΘΙΚΗ',     'Ethike',      'Ethics',                      'philosophical','historical'],
  ['ΠΟΛΙΤΙΚΗ',  'Politike',    'Politics',                    'philosophical','historical'],
  ['ΦΙΛΟΣΟΦΙΑ', 'Philosophia', 'Love of wisdom, Philosophy',  'philosophical','historical'],
  ['ΜΑΘΗΜΑΤΙΚΑ','Mathematika', 'Mathematics',                 'philosophical','historical'],
  ['ΑΣΤΡΟΝΟΜΙΑ','Astronomia',  'Astronomy',                   'philosophical','historical'],
  ['ΜΟΥΣΙΚΗ',   'Mousike',     'Music',                       'philosophical','historical'],
  ['ΓΕΩΜΕΤΡΙΑ', 'Geometria',   'Geometry',                    'philosophical','historical'],
  ['ΑΡΙΘΜΟΣ',   'Arithmos',    'Number',                      'philosophical','historical'],
  ['ΜΟΝΑΔΑ',    'Monas',       'Monad, Unit',                 'philosophical','historical'],
  ['ΔΥΑΔΑ',     'Dyas',        'Dyad, Pair',                  'philosophical','historical'],
  ['ΤΡΙΑΣ',     'Trias',       'Triad, Trinity',              'theological',  'historical'],
  ['ΤΕΤΡΑΣ',    'Tetras',      'Tetrad, Four',                'philosophical','historical'],
  ['ΔΕΚΑΣ',     'Dekas',       'Decade, Ten',                 'philosophical','historical'],
  ['ΑΠΕΙΡΟΝ',   'Apeiron',     'The Infinite (Anaximander)',  'philosophical','historical'],
  ['ΠΥΡ',       'Pyr',         'Fire (Heraclitus\'s principle)','philosophical','historical'],
  ['ΥΔΩΡ',      'Hydor',       'Water (Thales\'s principle)', 'philosophical','historical'],
  ['ΑΗΡ',       'Aer',         'Air (Anaximenes)',            'philosophical','historical'],
  ['ΓΗ',        'Ge',          'Earth (element)',             'philosophical','historical'],
  ['ΑΙΘΗΡ',     'Aither',      'Aether (fifth element)',      'philosophical','historical'],
  ['ΑΤΟΜΟΝ',    'Atomon',      'Atom (Democritus)',           'philosophical','historical'],
  ['ΚΕΝΟΝ',     'Kenon',       'Void, Empty space',           'philosophical','historical'],
  ['ΟΛΟΝ',      'Holon',       'Whole',                       'philosophical','historical'],
  ['ΜΕΡΟΣ',     'Meros',       'Part',                        'philosophical','mathematical'],
  ['ΣΥΝΟΛΟΝ',   'Synolon',     'Composite whole',             'philosophical','mathematical'],
  ['ΕΝΑΝΤΙΟΝ',  'Enantion',    'Opposite, Contrary',          'philosophical','mathematical'],
  ['ΣΥΜΠΑΝ',    'Sympan',      'Universe, All things',        'cosmological', 'mathematical'],

  // ── Theological / Biblical ────────────────────────────────────────────────
  ['ΠΑΤΗΡ',     'Pater',       'Father',                      'theological',  'historical'],
  ['ΥΙΟΣ',      'Huios',       'Son',                         'theological',  'historical'],
  ['ΑΓΙΟΣ',     'Hagios',      'Holy',                        'theological',  'historical'],
  ['ΕΚΚΛΗΣΙΑ',  'Ekklesia',    'Assembly, Church',            'theological',  'historical'],
  ['ΒΑΣΙΛΕΙΑ',  'Basileia',    'Kingdom',                     'theological',  'historical'],
  ['ΟΥΡΑΝΟΣ',   'Ouranos',     'Heaven, Sky',                 'theological',  'historical'],
  ['ΓΕΕΝΝΑ',    'Gehenna',     'Gehenna (place of torment)',  'theological',  'historical'],
  ['ΠΑΡΑΔΕΙΣΟΣ','Paradeisos',  'Paradise',                    'theological',  'historical'],
  ['ΑΜΑΡΤΙΑ',   'Hamartia',    'Sin, Error',                  'theological',  'mathematical'],
  ['ΜΕΤΑΝΟΙΑ',  'Metanoia',    'Repentance',                  'theological',  'mathematical'],
  ['ΠΙΣΤΙΣ',    'Pistis',      'Faith',                       'theological',  'mathematical'],
  ['ΕΛΠΙΣ',     'Elpis',       'Hope',                        'virtue',       'historical'],
  ['ΧΑΡΙΣ',     'Charis',      'Grace',                       'theological',  'historical'],
  ['ΔΟΞΑ',      'Doxa',        'Glory, Opinion',              'theological',  'historical'],
  ['ΧΑΡΙΣΜΑ',   'Charisma',    'Gift (of grace)',             'theological',  'mathematical'],
  ['ΠΡΟΦΗΤΗΣ',  'Prophetes',   'Prophet',                     'theological',  'mathematical'],
  ['ΑΠΟΣΤΟΛΟΣ', 'Apostolos',   'Apostle, Messenger',          'theological',  'mathematical'],
  ['ΕΥΑΓΓΕΛΙΟΝ','Euangelion',  'Gospel, Good news',           'theological',  'historical'],
  ['ΘΥΣΙΑ',     'Thysia',      'Sacrifice',                   'theological',  'mathematical'],
  ['ΒΑΠΤΙΣΜΑ',  'Baptisma',    'Baptism',                     'theological',  'mathematical'],
  ['ΠΑΡΟΥΣΙΑ',  'Parousia',    'Presence, Second coming',     'theological',  'historical'],
  ['ΑΠΟΚΑΛΥΨΙΣ','Apokalypsis', 'Revelation, Apocalypse',      'theological',  'historical'],
  ['ΣΩΤΗΡΙΑ',   'Soteria',     'Salvation',                   'theological',  'mathematical'],
  ['ΣΩΤΗΡ',     'Soter',       'Savior',                      'theological',  'mathematical'],
  ['ΙΕΡΕΥΣ',    'Hiereus',     'Priest',                      'theological',  'mathematical'],
  ['ΝΑΟΣ',      'Naos',        'Temple, Inner sanctuary',     'theological',  'mathematical'],
  ['ΘΥΣΙΑΣΤΗΡΙΟΝ','Thysiasterion','Altar',                    'theological',  'mathematical'],
  ['ΑΡΧΑΓΓΕΛΟΣ','Archangelos', 'Archangel',                   'theological',  'mathematical'],
  ['ΣΕΡΑΦΙΜ',   'Seraphim',    'Seraphim (heavenly beings)',  'theological',  'historical'],
  ['ΧΕΡΟΥΒΙΜ',  'Cherubim',    'Cherubim',                    'theological',  'historical'],
  ['ΣΑΤΑΝΑΣ',   'Satanas',     'Satan, Adversary',            'theological',  'historical'],
  ['ΔΙΑΒΟΛΟΣ',  'Diabolos',    'Devil, Slanderer',            'theological',  'historical'],
  ['ΑΒΥΣΣΟΣ',   'Abyssos',     'Abyss, Deep',                 'theological',  'mathematical'],
  ['ΜΥΣΤΗΡΙΟΝ', 'Mysterion',   'Mystery, Sacred secret',      'theological',  'historical'],
  ['ΘΕΟΤΗΤΑ',   'Theoteta',    'Divinity (abstract)',         'theological',  'mathematical'],
  ['ΠΑΝΤΟΚΡΑΤΩΡ','Pantokrator','Almighty, All-ruler',         'theological',  'historical'],
  ['ΛΟΓΙΟΝ',    'Logion',      'Oracle, Divine saying',       'theological',  'mathematical'],

  // ── Virtues & Ethics ──────────────────────────────────────────────────────
  ['ΔΙΚΑΙΟΣΥΝΗ','Dikaiosyne',  'Justice',                     'virtue',       'historical'],
  ['ΣΩΦΡΟΣΥΝΗ', 'Sophrosyne',  'Temperance, Self-control',    'virtue',       'historical'],
  ['ΑΝΔΡΕΙΑ',   'Andreia',     'Courage',                     'virtue',       'historical'],
  ['ΔΙΚΗ',      'Dike',        'Justice (divine/legal)',       'virtue',       'historical'],
  ['ΝΕΜΕΣΙΣ',   'Nemesis',     'Divine justice, Retribution', 'virtue',       'mathematical'],
  ['ΑΙΔΩΣ',     'Aidos',       'Shame, Reverence',            'virtue',       'historical'],
  ['ΣΕΜΝΟΤΗΣ',  'Semnotes',    'Dignity, Gravity',            'virtue',       'mathematical'],
  ['ΜΕΤΡΙΟΤΗΣ', 'Metriotetes', 'Moderation',                  'virtue',       'mathematical'],
  ['ΤΑΠΕΙΝΟΣ',  'Tapeinos',    'Humble',                      'virtue',       'mathematical'],
  ['ΤΑΠΕΙΝΩΣΙΣ','Tapeinosis',  'Humility',                    'virtue',       'mathematical'],
  ['ΠΡΑΟΤΗΣ',   'Praotes',     'Meekness, Gentleness',        'virtue',       'mathematical'],
  ['ΕΓΚΡΑΤΕΙΑ', 'Enkrateia',   'Self-control',                'virtue',       'mathematical'],
  ['ΜΑΚΑΡΙΟΣ',  'Makarios',    'Blessed, Happy',              'virtue',       'mathematical'],
  ['ΜΑΚΑΡΙΟΤΗΣ','Makariotes',  'Blessedness',                 'virtue',       'mathematical'],
  ['ΓΛΥΚΥΣ',    'Glykys',      'Sweet',                       'virtue',       'mathematical'],
  ['ΑΓΝΟΣ',     'Hagnos',      'Pure, Chaste',                'virtue',       'mathematical'],
  ['ΚΑΘΑΡΟΣ',   'Katharos',    'Clean, Pure',                 'virtue',       'mathematical'],
  ['ΑΛΗΘΗΣ',    'Alethes',     'True, Truthful',              'virtue',       'mathematical'],
  ['ΠΙΣΤΟΣ',    'Pistos',      'Faithful, Trustworthy',       'virtue',       'mathematical'],
  ['ΑΓΑΘΟΣΥΝΗ', 'Agathosyne',  'Goodness',                    'virtue',       'mathematical'],
  ['ΧΡΗΣΤΟΤΗΣ', 'Chrestotes',  'Kindness',                    'virtue',       'mathematical'],
  ['ΜΑΚΡΟΘΥΜΙΑ','Makrothymia', 'Patience, Long-suffering',    'virtue',       'mathematical'],
  ['ΕΥΣΕΒΕΙΑ',  'Eusebeia',    'Piety, Godliness',            'virtue',       'mathematical'],
  ['ΕΥΓΝΩΜΩΝ',  'Eugnomon',    'Grateful',                    'virtue',       'mathematical'],
  ['ΦΙΛΑΝΘΡΩΠΙΑ','Philanthropia','Love of humanity',          'virtue',       'mathematical'],
  ['ΦΙΛΑΔΕΛΦΙΑ','Philadelphia', 'Brotherly love',             'virtue',       'mathematical'],
  ['ΦΙΛΟΞΕΝΙΑ', 'Philoxenia',  'Hospitality to strangers',    'virtue',       'mathematical'],

  // ── Nature & Elements ─────────────────────────────────────────────────────
  ['ΗΛΙΟΣ',     'Helios',      'Sun',                         'nature',       'mathematical'],
  ['ΣΕΛΗΝΗ',    'Selene',      'Moon',                        'nature',       'mathematical'],
  ['ΑΣΤΗΡ',     'Aster',       'Star',                        'nature',       'mathematical'],
  ['ΟΥΡΑΝΟΣ',   'Ouranos',     'Sky',                         'nature',       'mathematical'],
  ['ΓΑΙΑ',      'Gaia',        'Earth',                       'nature',       'mathematical'],
  ['ΘΑΛΑΣΣΑ',   'Thalassa',    'Sea',                         'nature',       'mathematical'],
  ['ΠΟΤΑΜΟΣ',   'Potamos',     'River',                       'nature',       'mathematical'],
  ['ΟΡΕΑ',      'Orea',        'Mountains',                   'nature',       'mathematical'],
  ['ΝΕΦΕΛΗ',    'Nephele',     'Cloud',                       'nature',       'mathematical'],
  ['ΑΝΕΜΟΣ',    'Anemos',      'Wind',                        'nature',       'mathematical'],
  ['ΒΡΟΝΤΗ',    'Bronte',      'Thunder',                     'nature',       'mathematical'],
  ['ΑΣΤΡΑΠΗ',   'Astrape',     'Lightning',                   'nature',       'mathematical'],
  ['ΒΡΟΧΗ',     'Broche',      'Rain',                        'nature',       'mathematical'],
  ['ΧΙΩΝ',      'Chion',       'Snow',                        'nature',       'mathematical'],
  ['ΧΑΛΑΖΑ',    'Chalaza',     'Hail',                        'nature',       'mathematical'],
  ['ΑΝΟΙΞΙΣ',   'Anoixis',     'Spring (season)',             'nature',       'mathematical'],
  ['ΚΑΛΟΚΑΙΡΙ', 'Kalokairi',   'Summer',                      'nature',       'mathematical'],
  ['ΦΘΙΝΟΠΩΡΟ', 'Phthinoporo', 'Autumn',                      'nature',       'mathematical'],
  ['ΧΕΙΜΩΝΑΣ',  'Cheimonas',   'Winter',                      'nature',       'mathematical'],
  ['ΑΥΡΑ',      'Aura',        'Breeze',                      'nature',       'mathematical'],
  ['ΚΥΜΑ',      'Kyma',        'Wave',                        'nature',       'mathematical'],
  ['ΑΦΡΟΣ',     'Aphros',      'Foam',                        'nature',       'mathematical'],
  ['ΒΡΑΧΟΣ',    'Brachos',     'Rock',                        'nature',       'mathematical'],
  ['ΛΙΘΟΣ',     'Lithos',      'Stone',                       'nature',       'mathematical'],
  ['ΜΑΡΜΑΡΟ',   'Marmaro',     'Marble',                      'nature',       'mathematical'],
  ['ΧΡΥΣΟΣ',    'Chrysos',     'Gold',                        'nature',       'mathematical'],
  ['ΑΡΓΥΡΟΣ',   'Argyros',     'Silver',                      'nature',       'mathematical'],
  ['ΣΙΔΗΡΟΣ',   'Sideros',     'Iron',                        'nature',       'mathematical'],
  ['ΧΑΛΚΟΣ',    'Chalkos',     'Bronze, Copper',              'nature',       'mathematical'],
  ['ΞΥΛΟΝ',     'Xylon',       'Wood, Tree',                  'nature',       'mathematical'],
  ['ΔΕΝΔΡΟΝ',   'Dendron',     'Tree',                        'nature',       'mathematical'],
  ['ΑΝΘΟΣ',     'Anthos',      'Flower',                      'nature',       'mathematical'],
  ['ΚΑΡΠΟΣ',    'Karpos',      'Fruit',                       'nature',       'mathematical'],
  ['ΣΠΟΡΟΣ',    'Sporos',      'Seed',                        'nature',       'mathematical'],
  ['ΡΙΖΑ',      'Rhiza',       'Root',                        'nature',       'mathematical'],
  ['ΦΛΟΙΟΣ',    'Phloios',     'Bark (of tree)',              'nature',       'mathematical'],
  ['ΖΩΟΝ',      'Zoon',        'Animal, Living being',        'nature',       'mathematical'],
  ['ΙΧΘΥΣ',     'Ichthys',     'Fish',                        'nature',       'historical', 'Early Christian symbol'],
  ['ΛΕΩΝ',      'Leon',        'Lion',                        'nature',       'mathematical'],
  ['ΑΕΤΟΣ',     'Aetos',       'Eagle',                       'nature',       'mathematical'],
  ['ΠΕΡΙΣΤΕΡΑ',  'Peristera',   'Dove',                        'nature',       'mathematical'],
  ['ΔΡΑΚΩΝ',    'Drakon',      'Dragon, Serpent',             'myth',         'mathematical'],
  ['ΟΡΝΙΣ',     'Ornis',       'Bird',                        'nature',       'mathematical'],
  ['ΙΠΠΟΣ',     'Hippos',      'Horse',                       'nature',       'mathematical'],
  ['ΚΥΩΝ',      'Kyon',        'Dog',                         'nature',       'mathematical'],
  ['ΑΡΚΤΟΣ',    'Arktos',      'Bear',                        'nature',       'mathematical'],

  // ── Human Body & Life ─────────────────────────────────────────────────────
  ['ΚΕΦΑΛΗ',    'Kephale',     'Head',                        'body',         'mathematical'],
  ['ΚΑΡΔΙΑ',    'Kardia',      'Heart',                       'body',         'historical'],
  ['ΧΕΙΡ',      'Cheir',       'Hand',                        'body',         'mathematical'],
  ['ΠΟΔΕΣ',     'Podes',       'Feet',                        'body',         'mathematical'],
  ['ΟΜΜΑ',      'Omma',        'Eye',                         'body',         'mathematical'],
  ['ΟΦΘΑΛΜΟΣ',  'Ophthalmos',  'Eye',                         'body',         'mathematical'],
  ['ΩΤΑ',       'Ota',         'Ears',                        'body',         'mathematical'],
  ['ΣΤΟΜΑ',     'Stoma',       'Mouth',                       'body',         'mathematical'],
  ['ΓΛΩΣΣΑ',    'Glossa',      'Tongue, Language',            'body',         'mathematical'],
  ['ΡΙΝΑ',      'Rhina',       'Nose',                        'body',         'mathematical'],
  ['ΣΩΜΑ',      'Soma',        'Body',                        'body',         'mathematical'],
  ['ΑΙΜΑ',      'Haima',       'Blood',                       'body',         'mathematical'],
  ['ΣΑΡΞ',      'Sarx',        'Flesh',                       'body',         'historical'],
  ['ΟΣΤΕΟΝ',    'Osteon',      'Bone',                        'body',         'mathematical'],
  ['ΝΕΥΡΟΝ',    'Neuron',      'Sinew, Nerve',                'body',         'mathematical'],
  ['ΣΠΕΡΜΑ',    'Sperma',      'Seed, Semen',                 'body',         'mathematical'],
  ['ΕΜΒΡΥΟΝ',   'Embryon',     'Embryo',                      'body',         'mathematical'],
  ['ΤΕΚΝΟΝ',    'Teknon',      'Child',                       'body',         'mathematical'],
  ['ΑΝΗΡ',      'Aner',        'Man (adult male)',            'body',         'mathematical'],
  ['ΓΥΝΗ',      'Gyne',        'Woman',                       'body',         'mathematical'],
  ['ΝΕΑΝΙΑΣ',   'Neanias',     'Youth, Young man',            'body',         'mathematical'],
  ['ΓΗΡΑΣ',     'Geras',       'Old age',                     'body',         'mathematical'],
  ['ΓΕΝΝΗΣΙΣ',  'Gennesis',    'Birth, Generation',           'body',         'mathematical'],
  ['ΘΑΝΑΤΟΣ',   'Thanatos',    'Death',                       'concept',      'historical'],
  ['ΤΑΦΟΣ',     'Taphos',      'Tomb, Grave',                 'concept',      'mathematical'],
  ['ΑΝΑΣΤΑΣΙΣ', 'Anastasis',   'Resurrection',                'theological',  'historical'],

  // ── Emotions & States ─────────────────────────────────────────────────────
  ['ΛΥΠΗ',      'Lype',        'Grief, Sorrow',               'emotion',      'mathematical'],
  ['ΦΟΒΟΣ',     'Phobos',      'Fear',                        'emotion',      'mathematical'],
  ['ΘΥΜΟΣ',     'Thymos',      'Anger, Spirit',               'emotion',      'mathematical'],
  ['ΖΗΛΟΣ',     'Zelos',       'Zeal, Jealousy',              'emotion',      'mathematical'],
  ['ΗΔΟΝΗ',     'Hedone',      'Pleasure',                    'emotion',      'mathematical'],
  ['ΕΚΠΛΗΞΙΣ',  'Ekplexis',    'Astonishment',                'emotion',      'mathematical'],
  ['ΟΡΓΗ',      'Orge',        'Wrath, Anger',                'emotion',      'mathematical'],
  ['ΝΤΡΟΠΗ',    'Entrope',     'Shame',                       'emotion',      'mathematical'],
  ['ΑΓΑΝΑΚΤΗΣΙΣ','Aganaktesis','Indignation',                 'emotion',      'mathematical'],
  ['ΠΟΘΟΣ',     'Pothos',      'Longing, Desire',             'emotion',      'mathematical'],
  ['ΕΡΩΣ',      'Eros',        'Love (passionate)',           'emotion',      'historical'],
  ['ΣΤΕΡΓΩ',    'Stergo',      'Familial affection',          'emotion',      'mathematical'],
  ['ΕΧΘΡΑ',     'Echthra',     'Enmity, Hatred',              'emotion',      'mathematical'],
  ['ΖΗΛΟΤΥΠΙΑ', 'Zelotypia',   'Jealousy',                    'emotion',      'mathematical'],
  ['ΧΑΡΑ',      'Chara',       'Joy, Delight',                'emotion',      'mathematical'],
  ['ΕΛΠΙΔΑ',    'Elpida',      'Hope',                        'emotion',      'mathematical'],
  ['ΑΠΟΓΝΩΣΙΣ', 'Apognosis',   'Despair',                     'emotion',      'mathematical'],
  ['ΑΓΩΝΙΑ',    'Agonia',      'Agony, Anguish',              'emotion',      'mathematical'],
  ['ΘΑΥΜΑ',     'Thauma',      'Wonder, Marvel',              'emotion',      'historical'],
  ['ΕΚΣΤΑΣΙΣ',  'Ekstasis',    'Ecstasy',                     'emotion',      'mathematical'],

  // ── Society & Government ──────────────────────────────────────────────────
  ['ΔΗΜΟΣ',     'Demos',       'People, Democracy',           'concept',      'historical'],
  ['ΝΟΜΟΣ',     'Nomos',       'Law, Custom',                 'concept',      'historical'],
  ['ΒΑΣΙΛΕΥΣ',  'Basileus',    'King',                        'concept',      'historical'],
  ['ΤΥΡΑΝΝΟΣ',  'Tyrannos',    'Tyrant',                      'concept',      'historical'],
  ['ΑΡΙΣΤΟΚΡΑΤΙΑ','Aristokratia','Aristocracy',               'concept',      'historical'],
  ['ΔΗΜΟΚΡΑΤΙΑ','Demokratia',  'Democracy',                   'concept',      'historical'],
  ['ΠΟΛΙΤΗΣ',   'Polites',     'Citizen',                     'concept',      'historical'],
  ['ΕΛΕΥΘΕΡΙΑ', 'Eleutheria',  'Freedom, Liberty',            'virtue',       'historical'],
  ['ΙΣΟΤΗΣ',    'Isotes',      'Equality',                    'virtue',       'mathematical'],
  ['ΣΤΡΑΤΗΓΟΣ', 'Strategos',   'General, Commander',          'concept',      'mathematical'],
  ['ΠΟΛΕΜΟΣ',   'Polemos',     'War',                         'concept',      'historical'],
  ['ΕΙΡΗΝΗ',    'Eirene',      'Peace',                       'virtue',       'historical'],
  ['ΝΙΚΗ',      'Nike',        'Victory',                     'concept',      'mathematical'],
  ['ΗΤΤΑ',      'Hetta',       'Defeat',                      'concept',      'mathematical'],
  ['ΣΥΝΘΗΚΗ',   'Syntheke',    'Treaty, Agreement',           'concept',      'mathematical'],
  ['ΣΥΜΜΑΧΙΑ',  'Symmachia',   'Alliance',                    'concept',      'mathematical'],
  ['ΑΓΟΡΑ',     'Agora',       'Marketplace, Assembly',       'concept',      'historical'],
  ['ΕΚΚΛΗΣΙΑ',  'Ekklesia',    'Assembly (political)',        'concept',      'historical'],
  ['ΒΟΥΛΗ',     'Boule',       'Council',                     'concept',      'historical'],
  ['ΦΥΛΗ',      'Phyle',       'Tribe, Clan',                 'concept',      'mathematical'],

  // ── Time & Space ──────────────────────────────────────────────────────────
  ['ΧΡΟΝΟΣ',    'Chronos',     'Time',                        'cosmological', 'historical'],
  ['ΑΙΩΝ',      'Aion',        'Age, Eternity, Eon',          'cosmological', 'historical'],
  ['ΑΡΧΗ',      'Arche',       'Beginning, Origin',           'cosmological', 'historical'],
  ['ΤΕΛΟΣ',     'Telos',       'End, Culmination',            'cosmological', 'historical'],
  ['ΜΕΣΟΝ',     'Meson',       'Middle, Center',              'cosmological', 'mathematical'],
  ['ΧΩΡΑ',      'Chora',       'Space, Region (Plato)',       'cosmological', 'historical'],
  ['ΚΕΝΟΝ',     'Kenon',       'Void',                        'cosmological', 'historical'],
  ['ΠΛΗΡΩΜΑ',   'Pleroma',     'Fullness (Gnostic)',          'cosmological', 'historical'],
  ['ΜΕΓΕΘΟΣ',   'Megethos',    'Magnitude, Size',             'cosmological', 'mathematical'],
  ['ΚΙΝΗΣΙΣ',   'Kinesis',     'Movement, Change',            'cosmological', 'historical'],
  ['ΗΡΕΜΙΑ',    'Heremia',     'Rest, Stillness',             'cosmological', 'mathematical'],
  ['ΑΙΤΙΑ',     'Aitia',       'Cause',                       'cosmological', 'historical'],
  ['ΑΠΟΤΕΛΕΣΜΑ','Apotelesma',  'Result, Effect',              'cosmological', 'mathematical'],
  ['ΤΑΞΙΣ',     'Taxis',       'Order, Arrangement',          'cosmological', 'mathematical'],
  ['ΑΤΑΞΙΑ',    'Ataxia',      'Disorder, Chaos',             'cosmological', 'mathematical'],
  ['ΜΕΤΑΒΟΛΗ',  'Metabole',    'Change, Transformation',      'cosmological', 'mathematical'],
  ['ΓΕΝΕΣΙΣ',   'Genesis',     'Origin, Generation',          'cosmological', 'historical'],
  ['ΦΘΟΡΑ',     'Phthora',     'Decay, Corruption',           'cosmological', 'mathematical'],

  // ── Light & Knowledge ─────────────────────────────────────────────────────
  ['ΣΚΟΤΟΣ',    'Skotos',      'Darkness',                    'concept',      'historical'],
  ['ΣΚΙΑ',      'Skia',        'Shadow',                      'concept',      'mathematical'],
  ['ΛΑΜΨΙΣ',    'Lampsis',     'Radiance, Shining',           'concept',      'mathematical'],
  ['ΑΥΓΗ',      'Auge',        'Dawn, Radiance',              'concept',      'mathematical'],
  ['ΦΑΝΗΣ',     'Phanes',      'Appearance, Revealer',        'myth',         'historical'],
  ['ΕΚΦΑΝΣΙΣ',  'Ekphansis',   'Manifestation',               'concept',      'mathematical'],
  ['ΕΠΙΦΑΝΕΙΑ', 'Epiphaneia',  'Epiphany, Manifestation',     'theological',  'historical'],
  ['ΑΠΟΚΑΛΥΨΙΣ','Apokalypsis', 'Unveiling, Revelation',       'theological',  'historical'],
  ['ΚΡΥΠΤΗ',    'Krypte',      'Hidden, Secret',              'concept',      'mathematical'],
  ['ΜΥΣΤΗΡΙΟΝ', 'Mysterion',   'Mystery',                     'theological',  'historical'],
  ['ΓΝΩΣΙΣ',    'Gnosis',      'Knowledge',                   'philosophical','historical'],
  ['ΑΓΝΟΙΑ',    'Agnoia',      'Ignorance',                   'philosophical','mathematical'],
  ['ΜΝΗΜΗ',     'Mneme',       'Memory',                      'philosophical','mathematical'],
  ['ΑΝΑΜΝΗΣΙΣ', 'Anamnesis',   'Recollection (Plato)',        'philosophical','historical'],

  // ── Writing & Language ────────────────────────────────────────────────────
  ['ΑΛΦΑ',      'Alpha',       'Alpha (first letter)',        'concept',      'mathematical'],
  ['ΩΜΕΓΑ',     'Omega',       'Omega (last letter)',         'concept',      'mathematical'],
  ['ΓΡΑΜΜΑ',    'Gramma',      'Letter, Writing',             'concept',      'mathematical'],
  ['ΓΡΑΦΗ',     'Graphe',      'Writing, Scripture',          'concept',      'historical'],
  ['ΒΙΒΛΟΣ',    'Biblos',      'Book, Scroll',                'concept',      'historical'],
  ['ΕΠΙΣΤΟΛΗ',  'Epistole',    'Letter, Epistle',             'concept',      'historical'],
  ['ΠΟΙΗΜΑ',    'Poiema',      'Poem, Created work',          'concept',      'mathematical'],
  ['ΜΥΘΟΣ',     'Mythos',      'Myth, Story',                 'concept',      'historical'],
  ['ΙΣΤΟΡΙΑ',   'Historia',    'History, Inquiry',            'concept',      'historical'],
  ['ΤΡΑΓΩΔΙΑ',  'Tragodia',    'Tragedy',                     'concept',      'historical'],
  ['ΚΩΜΩΔΙΑ',   'Komodia',     'Comedy',                      'concept',      'historical'],
  ['ΕΠΟΣ',      'Epos',        'Epic poem, Word',             'concept',      'historical'],
  ['ΛΕΞΙΣ',     'Lexis',       'Word, Style, Diction',        'concept',      'historical'],
  ['ΡΗΜΑ',      'Rhema',       'Word, Verb',                  'concept',      'historical'],
  ['ΟΝΟΜΑ',     'Onoma',       'Name',                        'concept',      'mathematical'],
  ['ΑΡΙΘΜΟΣ',   'Arithmos',    'Number',                      'concept',      'historical'],
  ['ΣΗΜΕΙΟΝ',   'Semeion',     'Sign, Miracle',               'concept',      'historical'],
  ['ΣΥΜΒΟΛΟΝ',  'Symbolon',    'Symbol',                      'concept',      'historical'],
  ['ΕΙΚΩΝ',     'Eikon',       'Image, Icon',                 'concept',      'historical'],
  ['ΠΑΡΑΒΟΛΗ',  'Parabole',    'Parable, Comparison',         'concept',      'historical'],

  // ── Common Greek Words ────────────────────────────────────────────────────
  ['ΖΩΟΝ',      'Zoon',        'Animal',                      'nature',       'mathematical'],
  ['ΔΑΙΜΩΝ',    'Daimon',      'Spirit, Genius',              'concept',      'historical'],
  ['ΗΡΩΣ',      'Heros',       'Hero',                        'concept',      'historical'],
  ['ΒΑΡΒΑΡΟΣ',  'Barbaros',    'Foreigner, Barbarian',        'concept',      'historical'],
  ['ΔΟΥΛΟΣ',    'Doulos',      'Slave, Servant',              'concept',      'historical'],
  ['ΕΛΕΥΘΕΡΟΣ', 'Eleutheros',  'Free man',                    'virtue',       'historical'],
  ['ΦΙΛΟΣΟΦΟΣ', 'Philosophos', 'Lover of wisdom',             'philosophical','historical'],
  ['ΣΟΦΟΣ',     'Sophos',      'Wise man, Sage',              'philosophical','historical'],
  ['ΠΟΙΗΤΗΣ',   'Poietes',     'Poet, Creator',               'concept',      'historical'],
  ['ΡΗΤΩΡ',     'Rhetor',      'Orator, Speaker',             'concept',      'historical'],
  ['ΙΑΤΡΟΣ',    'Iatros',      'Physician',                   'concept',      'historical'],
  ['ΣΤΡΑΤΙΩΤΗΣ','Stratiotes',  'Soldier',                     'concept',      'mathematical'],
  ['ΝΑΥΤΗΣ',    'Nautes',      'Sailor',                      'concept',      'mathematical'],
  ['ΓΕΩΡΓΟΣ',   'Georgos',     'Farmer',                      'concept',      'mathematical'],
  ['ΤΕΧΝΙΤΗΣ',  'Technites',   'Craftsman, Artisan',          'concept',      'mathematical'],
  ['ΕΜΠΟΡΟΣ',   'Emporos',     'Merchant',                    'concept',      'mathematical'],
  ['ΒΑΣΙΛΕΙΑ',  'Basileia',    'Queen',                       'concept',      'mathematical'],

  // ── Numbers as words ──────────────────────────────────────────────────────
  ['ΜΟΝΑΣ',     'Monas',       'One, Monad (Pythagorean)',    'number_word',  'historical'],
  ['ΔΥΑΣ',      'Dyas',        'Two, Dyad (Pythagorean)',     'number_word',  'historical'],
  ['ΤΡΙΑΣ',     'Trias',       'Three, Triad',                'number_word',  'historical'],
  ['ΤΕΤΡΑΣ',    'Tetras',      'Four, Tetrad',                'number_word',  'historical'],
  ['ΠΕΝΤΑΣ',    'Pentas',      'Five, Pentad',                'number_word',  'historical'],
  ['ΕΞΑΣ',      'Hexas',       'Six, Hexad',                  'number_word',  'mathematical'],
  ['ΕΠΤΑΣ',     'Heptas',      'Seven, Heptad',               'number_word',  'mathematical'],
  ['ΟΚΤΩΣ',     'Oktos',       'Eight',                       'number_word',  'mathematical'],
  ['ΕΝΝΕΑΣ',    'Enneas',      'Nine, Ennead',                'number_word',  'mathematical'],
  ['ΔΕΚΑΣ',     'Dekas',       'Ten, Decad',                  'number_word',  'historical'],
  ['ΕΚΑΤΟΝ',    'Hekaton',     'Hundred',                     'number_word',  'mathematical'],
  ['ΧΙΛΙΟΙ',    'Chilioi',     'Thousand',                    'number_word',  'mathematical'],
];

// Deduplicate by word (keep first occurrence)
const seen = new Set();
const deduplicated = RAW_WORDS.filter(([word]) => {
  if (seen.has(word)) return false;
  seen.add(word);
  return true;
});

// Calculate and verify
let errors = 0;
const results = deduplicated.map(([word, trans, meaning, cat, itype, notes]) => {
  const computed = calc(word);
  return { word, trans, meaning, cat, itype, notes: notes || null, computed };
});

console.log(`Total words: ${results.length}`);
console.log('');

// Build TypeScript output
const tsLines = results.map(({ word, trans, meaning, cat, itype, notes, computed }) => {
  const notesStr = notes ? `, notes: ${JSON.stringify(notes)}` : '';
  const sourceStr = ['ΘΕΟΣ','ΙΗΣΟΥΣ','ΧΡΙΣΤΟΣ','ΛΟΓΟΣ','ΣΟΦΙΑ','ΝΟΥΣ','ΑΡΙΘΜΟΣ','ΦΙΛΟΣΟΦΙΑ'].includes(word)
    ? ', historicalSource: "Classical/Biblical Greek literature"' : '';
  return `  { word: '${word}', normalized: '${word}', value: ${computed}, transliteration: '${trans}', meaning: '${meaning}', category: '${cat}'${sourceStr}${notesStr}, interpretationType: '${itype}' },`;
});

console.log('export interface GreekWord {');
console.log("  word: string;");
console.log("  normalized: string;");
console.log("  value: number;");
console.log("  transliteration: string;");
console.log("  meaning: string;");
console.log("  category: 'theological' | 'philosophical' | 'virtue' | 'nature' | 'cosmological' | 'concept' | 'body' | 'emotion' | 'number_word' | 'myth';");
console.log("  notes?: string;");
console.log("  historicalSource?: string;");
console.log("  interpretationType: 'historical' | 'modern' | 'mathematical';");
console.log('}');
console.log('');
console.log('export const GREEK_WORDS: GreekWord[] = [');
tsLines.forEach(l => console.log(l));
console.log('];');
